### ISSUE TITLE
PopenAsUser Error

### ISSUE THREAD

**Issue by leocotes** [ni/jupyterhub-winlocalprocessspawner#14]
Hi guys.

I use windows server 2019. I try user **winlocalprocessspawner** and **ldapauthenticatorand** get this error on spawn:

[E 2022-12-08 11:19:40.739 JupyterHub user:832] Unhandled error starting user's server: PopenAsUser._execute_child() takes 19 positional arguments but 23 were given
    Traceback (most recent call last):
      File "G:\ProgramFiles\Python310\lib\site-packages\jupyterhub\user.py", line 747, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "G:\ProgramFiles\Python310\lib\site-packages\winlocalprocessspawner\winlocalprocessspawner.py", line 101, in start
        self.proc = PopenAsUser(cmd, **popen_kwargs)
      File "G:\ProgramFiles\Python310\lib\site-packages\winlocalprocessspawner\win_utils.py", line 126, in __init__
        super().__init__(args, bufsize, executable,
      File "G:\ProgramFiles\Python310\lib\subprocess.py", line 971, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
    TypeError: PopenAsUser._execute_child() takes 19 positional arguments but 23 were given

[E 2022-12-08 11:19:40.795 JupyterHub pages:311] Error starting server lferna14: PopenAsUser._execute_child() takes 19 positional arguments but 23 were given
    Traceback (most recent call last):
    NoneType: None

**My jupyterhub_config.py:**

c.JupyterHub.spawner_class = 'winlocalprocessspawner.WinLocalProcessSpawner'
c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'

c.LDAPAuthenticator.server_address = 'hostname'
c.LDAPAuthenticator.lookup_dn = True
c.LDAPAuthenticator.lookup_dn_search_user = 'user'
c.LDAPAuthenticator.lookup_dn_search_password = 'pass'
c.LDAPAuthenticator.user_search_base = 'DC=,DC='
c.LDAPAuthenticator.user_attribute = 'mail'
c.LDAPAuthenticator.lookup_dn_user_dn_attribute = 'sAMAccountName'
c.LDAPAuthenticator.valid_username_regex = '^[a-z][.a-z0-9@_-]*$'
c.Spawner.cmd = 'jupyter-lab'

**I tried use c.JupyterHub.authenticator_class = 'winauthenticator.WinAuthenticator', i got the same PoprnAsUser error.**

The version jupyterhub==3.1.0 and python 3.10.9.

Is this will works in my environment?

**Comment by adelcast** [comment]
Hi @leocotes, thanks for reaching out

I haven't tested the spawner/authenticator on Windows Server 2019, but I don't think the interfaces have changed. Might require a bit of digging/debugging to figure out what's going on though. Since the winlocalprocessspawner relies on an auth token created at authentication time, it will not work with "vanilla" authenticators that don't fill the token. My suggestion would be to do the debugging using the winlocalprocessspawner/winauthenticator combination. 

You mentioned with that combination you are getting the same error.....did you enable the auth_state and set JUPYTERHUB_CRYPT_KEY  per https://github.com/ni/jupyterhub-winauthenticator?

The error also mentions 23 parameters passed to PopeAsUser, instead of 19. Maybe you could print the parameters to see why they don't match?

**Comment by hsluoyz** [comment]
@adelcast @leocotes hi, this PR: https://github.com/ni/jupyterhub-winlocalprocessspawner/pull/15 will resolve it
